### ISSUE TITLE
Cannot open Teensy board files in EAGLE

### ISSUE THREAD

**Issue by roy-zahor** [HCIELab/EIT-kit_open-source#6]
Hi,

New verison files in [EIT-kit-Board_new](https://github.com/HCIELab/EIT-kit_open-source/tree/main/EIT-kit-Board_new) 
cannot be open in eagle. Both schematic and PCB files give warnings and files are partially opened. I can open the ESP32 files without a problem.

1. Is the Teensy version stable in terms of hardware & software or do you recommend using the ESP32 version?
2. Can you please check the files?

Many thanks,
Roy

**Comment by junyi7** [comment]
Hi Roy,

Sorry for the confusion! Please try using Fusion 360 to open the new files rather than EAGLE, we switched the new files to Fusion 360 because EAGLE is discontinued and no longer supported by Autodesk, and they promotes everything to Fusion 360 instead. And yes, the Teensy version is more stable in terms of the hardware (more stable GPIO pin readings at high speed).

Best,
Junyi
